### PR TITLE
Expviewer does not display after latest merge when changing channels

### PR DESCRIPTION
**Pull request by cyrilpangilinan**
Fixed init call reference, as when changing channels, the expviewer does not display.

### CODE REVIEW

**Comment by zckrs** [comment]
Maybe you canapply the new hook system like others addons 
https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/commit/68314a44b805b5a8b45184020f35938a4998dc39

**Comment by cyrilpangilinan** [comment]
Sure, already testing

**Comment by zckrs** [comment]
:+1:

**Comment by TehSeph** [comment]
Might be worthwhile to rename the ExpViewer `INIT()` as well (and any other addons using the same function name.)

**Comment by Excrulon** [comment]
I'm going to redo all the exp functions so they aren't on the global scope.
As good practice we shouldn't be using anything on _G unless absolutely
needed.

**Comment by TehSeph** [comment]
Agreed. Globals are bad.

**Pull request merged**
