### PR TITLE
channelsurfer - added buttons for previous/next channel

### PR DESCRIPTION
**Pull request by Miei**
[preview](https://i.imgur.com/IgJLY0a.png)

### CODE REVIEW

**Comment by Miei** [comment]
[moved to separate addon](https://github.com/Miei/TOS-lua/blob/master/channelsurferbuttons/channelsurferbuttons.lua)

**Comment by Excrulon** [comment]
I like the buttons, was wanting to add them myself anyway since I couldn't
get a global hotkey working for it.

**Comment by Miei** [comment]
Well, the code is there if you want to use it, but I have moved it to a separate addon [here](https://github.com/Miei/TOS-lua/blob/master/channelsurferbuttons/channelsurferbuttons.lua) for now, so that it can work independently. It's up to you.

**Comment by Excrulon** [comment]
Right, but can you just reopen this so it's easy to merge?

**Comment by Miei** [comment]
Woops, I had deleted my fork though. I made a [new pull request](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/pull/54) instead.

**Pull request closed without merging**
