### PR TITLE
add hook to create checkbox on ui init

### PR DESCRIPTION
**Pull request by Miei**
Otherwise the checkbox will be missing after a loading screen.

### CODE REVIEW

**Comment by TehSeph** [comment]
Changes made in #56 to the lines
```
_G['OLD_POSSIBLE_UI_OPEN_CHECK'] = _G['SCR_POSSIBLE_UI_OPEN_CHECK'];
_G['SCR_POSSIBLE_UI_OPEN_CHECK'] = BETTERQUEST_POSSIBLE_UI_OPEN_CHECK;
_G['OLD_UPDATE_ALLQUEST'] = _G['UPDATE_ALLQUEST'];
_G['UPDATE_ALLQUEST'] = BETTERQUEST_UPDATE_ALLQUEST;
```
to
```
SETUP_HOOK(BETTERQUEST_POSSIBLE_UI_OPEN_CHECK, "SCR_POSSIBLE_UI_OPEN_CHECK");
SETUP_HOOK(BETTERQUEST_UPDATE_ALLQUEST, "UPDATE_ALLQUEST");
```
are reverted by this merge. Just a heads up. :+1:

**Comment by Excrulon** [comment]
I think I messed up the merge. (PS: I hate git)

**Comment by TehSeph** [comment]
(everyone hates git)

**Comment by Excrulon** [comment]
I don't really know what you're saying. Are you saying these lines need to be added back?

```lua
SETUP_HOOK(BETTERQUEST_POSSIBLE_UI_OPEN_CHECK, "SCR_POSSIBLE_UI_OPEN_CHECK");
SETUP_HOOK(BETTERQUEST_UPDATE_ALLQUEST, "UPDATE_ALLQUEST");
```

**Comment by TehSeph** [comment]
The code is back after this was merged, since it conflicted with the new lines from #56, so the latest `betterquest.lua` file in the repo is using the old method not the `SETUP_HOOK()` method.

**Comment by Excrulon** [comment]
I'm not seeing that...

**Comment by Excrulon** [comment]
Oh, I see now. Not quite sure what people were trying to do here.

**Comment by TehSeph** [comment]
Basically two different fixes on the same file at the same time, in the same place, without waiting for one to get merged first. Big git no-no. lol

**Comment by TehSeph** [comment]
Small thing. I would have just patched it myself but seems like a dumb thing to open a 3rd PR for.

**Comment by Excrulon** [comment]
I don't want to do it right now, in the middle of trying to finish something else up. Will get around to it eventually but if you or someone else made a PR for it, that'd be much appreciated!

**Pull request merged**
