### PR TITLE
adding a section to status ui to show points invested into each stat

### PR DESCRIPTION
**Pull request by mc-crafty**
cleaned up branches and reforked from your latest changes. sorry for the pull spam

this adds nice to have stat related methods in the utilities and will show invested points in the Status menu. 
The stat calc on TOS base is wildly inaccurate as ToS adds all sorts of odd bonuses to stats, allows extra stat allocation (such as stats obtained from goddess statues), and generally shows very little as to how it actually calculates things. Even the SCR stat methods don't come up with the displayed amount...

### CODE REVIEW

**Comment by zckrs** [comment]
:100:

**Comment by vincentraulic** [comment]
This is not working for me, i have nothing added in the stat UI

**Comment by Excrulon** [comment]
I'll try out your mod tonight I guess if I have time.

**Comment by zckrs** [comment]
Tested, LGTM.

showinvestedstatpoints

**Comment by pedrosotero** [comment]
Tested it works, alread merge this to my game also with the betterquest from the other pull request

**Comment by MrJustMe** [comment]
Nice!, i almost can't wait to see this feature running inside the game already :p

**Pull request merged**
