### PR TITLE
Update blockandreport.lua

### PR DESCRIPTION
**Pull request by Miei**
add "character info" to context menu
remove redundant context menu entries
fix a bug that would automatically 'like' target player when opening character information from the party window

### CODE REVIEW

**Comment by TehSeph** [comment]
The `SHOW_PC_CONTEXT_MENU` stuff was for when you right-click a character ingame. If you're going to remove that and merge report and block into a single function you'll need to remove `BLOCK_AND_REPORT` and in it's place change the default `REPORT_AUTOBOT_MSGBOX` function. :)

**Comment by Miei** [comment]
That's what this hook does, no?
`SETUP_HOOK(BLOCK_AND_REPORT, "REPORT_AUTOBOT_MSGBOX");`

I guess I can rename it if you want.

**Comment by TehSeph** [comment]
Ah yeah didn't noticed it was being hooked because of the name. My bad.

**Comment by Miei** [comment]
After much debate on discord (ocd galore), should be ready to merge.

**Comment by TehSeph** [comment]
Squash commits? :stuck_out_tongue:

**Pull request merged**
