### PR TITLE
channelsurfer -- added buttons for previous/next channel

### PR DESCRIPTION
**Pull request by Miei**

### CODE REVIEW

**Comment by Excrulon** [comment]
Thanks, I appreciate it!

**Comment by TehSeph** [comment]
Could we get an option to disable these? Not a fan of things being layered over the minimap.

**Comment by Excrulon** [comment]
Yeah I'll do that.

**Comment by cyrilpangilinan** [comment]
@Excrulon Would it be better to have a config file in the root directory for addons and make them configurable (enabled/disabled) since your mods come in a 'suite'?

**Comment by fiote** [comment]
@cyrilpangilinan Ingame edit is better. Too bad its hard as hell without being able to load custom xmls.

**Comment by Excrulon** [comment]
Yep definitely. I'm planning to have an api all addons can use to have an
option to change things through the system menu at the bottom right. Easy
to read/write config files with lua file commands.

**Pull request merged**
